### ISSUE TITLE
Monitoring Stack Anomaly 

### ISSUE THREAD

**Issue by umangachapagain** [gluster/gcs#115]
**1. Prometheus Server Configuration**
```
[vagrant@kube1 ~]$ kubectl exec -ti prometheus-prometheus-0 -ngcs -- cat /etc/prometheus/prometheus.yml
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

```
Same output for,
`[vagrant@kube1 ~]$ kubectl exec -ti prometheus-prometheus-1 -ngcs -- cat /etc/prometheus/prometheus.yml`

Looks like prometheus server pods are using the default configurations. Shouldn't this be configured to talk to `alertmanager` and scrape `gluster-exporter`? Currently, prometheus server only exposes it's own metrics.
```
[vagrant@kube1 ~]$ curl 10.233.30.229:9090/metrics | grep gluster_
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 74677  100 74677    0     0  5507k      0 --:--:-- --:--:-- --:--:-- 5609k

```

```
[vagrant@kube1 ~]$ kubectl get po prometheus-prometheus-0 -ngcs -oyaml

spec:
  containers:
  - args:
    - --web.console.templates=/etc/prometheus/consoles
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention=24h
    - --web.enable-lifecycle
    - --storage.tsdb.no-lockfile
    - --web.route-prefix=/
. . . .
 - args:
    - --log-format=logfmt
    - --reload-url=http://localhost:9090/-/reload
    - --config-file=/etc/prometheus/config/prometheus.yaml
    - --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
```

` - --config-file=/etc/prometheus/config/prometheus.yaml`
This path does not exist. (Probably because we are not providing it?)

```
[vagrant@kube1 ~]$ kubectl exec -ti  prometheus-prometheus-0 -ngcs -- ls /etc/prometheus/
config_out         consoles           rules         console_libraries  prometheus.yml
```
So, Prometheus Server is being configured with default setting through,
` - --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml`
This scrapes all given endpoints.

**2. Metrics scraped directly from Kubernetes Endpoints**
```
[vagrant@kube1 ~]$ kubectl get endpoints -ngcs | grep glusterd2-client
glusterd2-client            10.233.64.7:8080,10.233.65.4:8080,10.233.66.9:8080 + 3 more...      150m
```
This can be found at `node-ip:30600/targets`

Ideally, this behavior fine, but looking at the code, seems like that is not the expected way.
These endpoints should be scraped by prometheus from a `service` endpoint via `servicemonitor` which is what the code attempts to do, but is failing because of erroneous deployment of the stack.

**3. Metrics inconsistent between Prometheus Server Endpoint & Glusterd2-client endpoint**

Scraping from the `glusterd2-client` service endpoint,
```
[vagrant@kube1 ~]$ kubectl get svc -ngcs|grep glusterd2-client
glusterd2-client            ClusterIP   10.233.5.157    <none>        24007/TCP,8080/TCP    158m

[vagrant@kube1 ~]$ curl 10.233.5.157:8080/metrics|grep gluster_
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10994  100 10994    0     0  1633k      0 --:--:-- --:--:-- --:--:-- 2147k
# HELP gluster_brick_capacity_bytes_total Total capacity of gluster bricks in bytes
# TYPE gluster_brick_capacity_bytes_total gauge
gluster_brick_capacity_bytes_total{brick_path="/var/run/glusterd2/bricks/pvc-8b5d5507-1590-11e9-885f-5254000701ba/subvol1/brick2/brick",host="gluster-kube1-0.glusterd2.gcs",id="23f0dfaa-8e38-47a1-8e40-b9b78a915fbf",subvolume="pvc-8b5d5507-1590-11e9-885f-5254000701ba-replicate-0",volume="pvc-8b5d5507-1590-11e9-885f-5254000701ba"} 5.356126208e+09
# HELP gluster_brick_capacity_free_bytes Free capacity of gluster bricks in bytes
# TYPE gluster_brick_capacity_free_bytes gauge
gluster_brick_capacity_free_bytes{brick_path="/var/run/glusterd2/bricks/pvc-8b5d5507-1590-11e9-885f-5254000701ba/subvol1/brick2/brick",host="gluster-kube1-0.glusterd2.gcs",id="23f0dfaa-8e38-47a1-8e40-b9b78a915fbf",subvolume="pvc-8b5d5507-1590-11e9-885f-5254000701ba-replicate-0",volume="pvc-8b5d5507-1590-11e9-885f-5254000701ba"} 5.322027008e+09
# HELP gluster_brick_capacity_used_bytes Used capacity of gluster bricks in bytes
# TYPE gluster_brick_capacity_used_bytes gauge
gluster_brick_capacity_used_bytes{brick_path="/var/run/glusterd2/bricks/pvc-8b5d5507-1590-11e9-885f-5254000701ba/subvol1/brick2/brick",host="gluster-kube1-0.glusterd2.gcs",id="23f0dfaa-8e38-47a1-8e40-b9b78a915fbf",subvolume="pvc-8b5d5507-1590-11e9-885f-5254000701ba-replicate-0",volume="pvc-8b5d5507-1590-11e9-885f-5254000701ba"} 3.40992e+07
```

Scraping from the `prometheus` service endpoint,
```
[vagrant@kube1 ~]$ kubectl get svc -ngcs|grep prometheus
prometheus                  NodePort    10.233.30.229   <none>        9090:30600/TCP        153m

[vagrant@kube1 ~]$ curl 10.233.30.229:9090/metrics|grep gluster_
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 78432  100 78432    0     0  1903k      0 --:--:-- --:--:-- --:--:-- 1963k
```

Shouldn't this `prometheus` `NodePort` mapped to `30600` for external use be exposing gluster metrics at `node-ip:30600/metrics` ?

**4. Prometheus is not picking up ServiceMonitor for monitoring**

https://github.com/gluster/gcs/blob/master/deploy/templates/gcs-manifests/gcs-prometheus-bundle.yml.j2#L73

**5. Alertmanager depends on prometheus configuration.**
From the output given in point 1,
```
# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093
```
Looks like prometheus server is not configured to talk to alertmanager. So, even if alerts are generated, it won't reach the slack or email webhook provided via secret.

These are few things that are confusing and maybe I am misunderstanding something or these are issues on my end. Would like to have a discussion on this.
@sidharthanup @JohnStrunk @shtripat
