### ISSUE TITLE
Grafana dashboard not showing gluster volumes

### ISSUE THREAD

**Issue by JohnStrunk** [gluster/gcs#134]
During testing for GCS 1.0-pre, the Grafana dashboard is not displaying metrics for gluster volumes.

Once GCS is deployed, I created the following workload in namespace `test`:

```
$ kubectl --kubeconfig=kubeconfig apply -n test -f scratch/test-glusterfs.yml
```

```yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-glusterfs
spec:
  storageClassName: glusterfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: batch/v1
kind: Job
metadata:
  name: fs-performance
spec:
  template:
    metadata:
      name: fs-performance
    spec:
      containers:
        - name: fio
          image: quay.io/johnstrunk/fs-performance:latest
          args: ["clone", "kernel"]
          env:
            - name: TARGET_CAPACITY_MB
              value: "500"
            - name: TARGET_PATH
              value: "/target"
            - name: CLONE_REPO
              value: "https://github.com/gluster/glusterfs.git"
          volumeMounts:
            - name: target
              mountPath: /target
      restartPolicy: Never
      volumes:
        - name: target
          persistentVolumeClaim:
            claimName: test-glusterfs
```

After the workload started, I viewed the gluster Grafana dashboard, and the "Volume" dropdown only had the entry "None". All graphs either displayed "N/A" or "no data points". Datasource was the default: "Prometheus"
