### ISSUE TITLE
Tracker: Enable thin arbiter

### ISSUE THREAD

**Issue by JohnStrunk** [gluster/gcs#54]
- Add support for thin arbiter to CSI driver
  - [ ] Parent of gluster/gluster-csi-driver#46

**Comment by JohnStrunk** [comment]
@amarts In the CSI driver, we have defined (but not implemented) the following parameters:

```yaml
parameters:
  # Type of arbiter for replicate volumes. default=none
￼  arbiterType: none  # (none | normal | thin)
  # Supplying arbiterZones restricts the placement of arbiter bricks to the
  # provided zone(s). Only applicable for replicate volumes with arbiter. If
  # not specified, dataZones will be used.
  arbiterZones: "az4,az5"
```

Zones, above, are supposed to use node tags via IVP to do placement.

Are we missing any parameters or do we just need to prioritize appropriately?
